// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session_service.proto

package ru.weber.auth.service.service.grpc;

public final class SessionServiceOuterClass {
  private SessionServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetSessionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.weber.auth.service.service.grpc.GetSessionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code ru.weber.auth.service.service.grpc.GetSessionRequest}
   */
  public  static final class GetSessionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.weber.auth.service.service.grpc.GetSessionRequest)
      GetSessionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetSessionRequest.newBuilder() to construct.
    private GetSessionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetSessionRequest() {
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetSessionRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetSessionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_GetSessionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_GetSessionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest.class, ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest.Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest)) {
        return super.equals(obj);
      }
      ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest other = (ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest) obj;

      if (!getToken()
          .equals(other.getToken())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.weber.auth.service.service.grpc.GetSessionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.weber.auth.service.service.grpc.GetSessionRequest)
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_GetSessionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_GetSessionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest.class, ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest.Builder.class);
      }

      // Construct using ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        token_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_GetSessionRequest_descriptor;
      }

      @java.lang.Override
      public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest getDefaultInstanceForType() {
        return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest build() {
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest buildPartial() {
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest result = new ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest(this);
        result.token_ = token_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest) {
          return mergeFrom((ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest other) {
        if (other == ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest.getDefaultInstance()) return this;
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.weber.auth.service.service.grpc.GetSessionRequest)
    }

    // @@protoc_insertion_point(class_scope:ru.weber.auth.service.service.grpc.GetSessionRequest)
    private static final ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest();
    }

    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetSessionRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetSessionRequest>() {
      @java.lang.Override
      public GetSessionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetSessionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetSessionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetSessionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SetSessionInvalidRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.weber.auth.service.service.grpc.SetSessionInvalidRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code ru.weber.auth.service.service.grpc.SetSessionInvalidRequest}
   */
  public  static final class SetSessionInvalidRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.weber.auth.service.service.grpc.SetSessionInvalidRequest)
      SetSessionInvalidRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SetSessionInvalidRequest.newBuilder() to construct.
    private SetSessionInvalidRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SetSessionInvalidRequest() {
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SetSessionInvalidRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SetSessionInvalidRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_SetSessionInvalidRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_SetSessionInvalidRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest.class, ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest.Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest)) {
        return super.equals(obj);
      }
      ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest other = (ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest) obj;

      if (!getToken()
          .equals(other.getToken())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.weber.auth.service.service.grpc.SetSessionInvalidRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.weber.auth.service.service.grpc.SetSessionInvalidRequest)
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_SetSessionInvalidRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_SetSessionInvalidRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest.class, ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest.Builder.class);
      }

      // Construct using ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        token_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_SetSessionInvalidRequest_descriptor;
      }

      @java.lang.Override
      public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest getDefaultInstanceForType() {
        return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest build() {
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest buildPartial() {
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest result = new ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest(this);
        result.token_ = token_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest) {
          return mergeFrom((ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest other) {
        if (other == ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest.getDefaultInstance()) return this;
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.weber.auth.service.service.grpc.SetSessionInvalidRequest)
    }

    // @@protoc_insertion_point(class_scope:ru.weber.auth.service.service.grpc.SetSessionInvalidRequest)
    private static final ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest();
    }

    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SetSessionInvalidRequest>
        PARSER = new com.google.protobuf.AbstractParser<SetSessionInvalidRequest>() {
      @java.lang.Override
      public SetSessionInvalidRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetSessionInvalidRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SetSessionInvalidRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SetSessionInvalidRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetSessionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru.weber.auth.service.service.grpc.GetSessionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; meta_info = 1;</code>
     */
    int getMetaInfoCount();
    /**
     * <code>map&lt;string, string&gt; meta_info = 1;</code>
     */
    boolean containsMetaInfo(
        java.lang.String key);
    /**
     * Use {@link #getMetaInfoMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMetaInfo();
    /**
     * <code>map&lt;string, string&gt; meta_info = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMetaInfoMap();
    /**
     * <code>map&lt;string, string&gt; meta_info = 1;</code>
     */

    java.lang.String getMetaInfoOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; meta_info = 1;</code>
     */

    java.lang.String getMetaInfoOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code ru.weber.auth.service.service.grpc.GetSessionResponse}
   */
  public  static final class GetSessionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru.weber.auth.service.service.grpc.GetSessionResponse)
      GetSessionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetSessionResponse.newBuilder() to construct.
    private GetSessionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetSessionResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetSessionResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetSessionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                metaInfo_ = com.google.protobuf.MapField.newMapField(
                    MetaInfoDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              metaInfo__ = input.readMessage(
                  MetaInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              metaInfo_.getMutableMap().put(
                  metaInfo__.getKey(), metaInfo__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMetaInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.class, ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.Builder.class);
    }

    public static final int META_INFO_FIELD_NUMBER = 1;
    private static final class MetaInfoDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_MetaInfoEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metaInfo_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMetaInfo() {
      if (metaInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetaInfoDefaultEntryHolder.defaultEntry);
      }
      return metaInfo_;
    }

    public int getMetaInfoCount() {
      return internalGetMetaInfo().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; meta_info = 1;</code>
     */

    public boolean containsMetaInfo(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMetaInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetaInfoMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetaInfo() {
      return getMetaInfoMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta_info = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getMetaInfoMap() {
      return internalGetMetaInfo().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta_info = 1;</code>
     */

    public java.lang.String getMetaInfoOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetaInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; meta_info = 1;</code>
     */

    public java.lang.String getMetaInfoOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetaInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMetaInfo(),
          MetaInfoDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMetaInfo().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        metaInfo__ = MetaInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, metaInfo__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse)) {
        return super.equals(obj);
      }
      ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse other = (ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse) obj;

      if (!internalGetMetaInfo().equals(
          other.internalGetMetaInfo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetMetaInfo().getMap().isEmpty()) {
        hash = (37 * hash) + META_INFO_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMetaInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru.weber.auth.service.service.grpc.GetSessionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru.weber.auth.service.service.grpc.GetSessionResponse)
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMetaInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableMetaInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.class, ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.Builder.class);
      }

      // Construct using ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableMetaInfo().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_descriptor;
      }

      @java.lang.Override
      public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse getDefaultInstanceForType() {
        return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse build() {
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse buildPartial() {
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse result = new ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse(this);
        int from_bitField0_ = bitField0_;
        result.metaInfo_ = internalGetMetaInfo();
        result.metaInfo_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse) {
          return mergeFrom((ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse other) {
        if (other == ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.getDefaultInstance()) return this;
        internalGetMutableMetaInfo().mergeFrom(
            other.internalGetMetaInfo());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> metaInfo_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMetaInfo() {
        if (metaInfo_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetaInfoDefaultEntryHolder.defaultEntry);
        }
        return metaInfo_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMetaInfo() {
        onChanged();;
        if (metaInfo_ == null) {
          metaInfo_ = com.google.protobuf.MapField.newMapField(
              MetaInfoDefaultEntryHolder.defaultEntry);
        }
        if (!metaInfo_.isMutable()) {
          metaInfo_ = metaInfo_.copy();
        }
        return metaInfo_;
      }

      public int getMetaInfoCount() {
        return internalGetMetaInfo().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; meta_info = 1;</code>
       */

      public boolean containsMetaInfo(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMetaInfo().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMetaInfoMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMetaInfo() {
        return getMetaInfoMap();
      }
      /**
       * <code>map&lt;string, string&gt; meta_info = 1;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getMetaInfoMap() {
        return internalGetMetaInfo().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; meta_info = 1;</code>
       */

      public java.lang.String getMetaInfoOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetaInfo().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; meta_info = 1;</code>
       */

      public java.lang.String getMetaInfoOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetaInfo().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMetaInfo() {
        internalGetMutableMetaInfo().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; meta_info = 1;</code>
       */

      public Builder removeMetaInfo(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMetaInfo().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMetaInfo() {
        return internalGetMutableMetaInfo().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; meta_info = 1;</code>
       */
      public Builder putMetaInfo(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMetaInfo().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; meta_info = 1;</code>
       */

      public Builder putAllMetaInfo(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMetaInfo().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ru.weber.auth.service.service.grpc.GetSessionResponse)
    }

    // @@protoc_insertion_point(class_scope:ru.weber.auth.service.service.grpc.GetSessionResponse)
    private static final ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse();
    }

    public static ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetSessionResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetSessionResponse>() {
      @java.lang.Override
      public GetSessionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetSessionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetSessionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetSessionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code ru.weber.auth.service.service.grpc.SessionService}
   */
  public static abstract class SessionService
      implements com.google.protobuf.Service {
    protected SessionService() {}

    public interface Interface {
      /**
       * <code>rpc GetSession(.ru.weber.auth.service.service.grpc.GetSessionRequest) returns (.ru.weber.auth.service.service.grpc.GetSessionResponse);</code>
       */
      public abstract void getSession(
          com.google.protobuf.RpcController controller,
          ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest request,
          com.google.protobuf.RpcCallback<ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse> done);

      /**
       * <code>rpc InvalidateSession(.ru.weber.auth.service.service.grpc.SetSessionInvalidRequest) returns (.google.protobuf.Empty);</code>
       */
      public abstract void invalidateSession(
          com.google.protobuf.RpcController controller,
          ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest request,
          com.google.protobuf.RpcCallback<com.google.protobuf.Empty> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new SessionService() {
        @java.lang.Override
        public  void getSession(
            com.google.protobuf.RpcController controller,
            ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest request,
            com.google.protobuf.RpcCallback<ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse> done) {
          impl.getSession(controller, request, done);
        }

        @java.lang.Override
        public  void invalidateSession(
            com.google.protobuf.RpcController controller,
            ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest request,
            com.google.protobuf.RpcCallback<com.google.protobuf.Empty> done) {
          impl.invalidateSession(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getSession(controller, (ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest)request);
            case 1:
              return impl.invalidateSession(controller, (ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest.getDefaultInstance();
            case 1:
              return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.getDefaultInstance();
            case 1:
              return com.google.protobuf.Empty.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc GetSession(.ru.weber.auth.service.service.grpc.GetSessionRequest) returns (.ru.weber.auth.service.service.grpc.GetSessionResponse);</code>
     */
    public abstract void getSession(
        com.google.protobuf.RpcController controller,
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest request,
        com.google.protobuf.RpcCallback<ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse> done);

    /**
     * <code>rpc InvalidateSession(.ru.weber.auth.service.service.grpc.SetSessionInvalidRequest) returns (.google.protobuf.Empty);</code>
     */
    public abstract void invalidateSession(
        com.google.protobuf.RpcController controller,
        ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest request,
        com.google.protobuf.RpcCallback<com.google.protobuf.Empty> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getSession(controller, (ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest)request,
            com.google.protobuf.RpcUtil.<ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse>specializeCallback(
              done));
          return;
        case 1:
          this.invalidateSession(controller, (ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest)request,
            com.google.protobuf.RpcUtil.<com.google.protobuf.Empty>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest.getDefaultInstance();
        case 1:
          return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.getDefaultInstance();
        case 1:
          return com.google.protobuf.Empty.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SessionService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getSession(
          com.google.protobuf.RpcController controller,
          ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest request,
          com.google.protobuf.RpcCallback<ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.class,
            ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.getDefaultInstance()));
      }

      public  void invalidateSession(
          com.google.protobuf.RpcController controller,
          ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest request,
          com.google.protobuf.RpcCallback<com.google.protobuf.Empty> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.google.protobuf.Empty.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.google.protobuf.Empty.class,
            com.google.protobuf.Empty.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse getSession(
          com.google.protobuf.RpcController controller,
          ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest request)
          throws com.google.protobuf.ServiceException;

      public com.google.protobuf.Empty invalidateSession(
          com.google.protobuf.RpcController controller,
          ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse getSession(
          com.google.protobuf.RpcController controller,
          ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionRequest request)
          throws com.google.protobuf.ServiceException {
        return (ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          ru.weber.auth.service.service.grpc.SessionServiceOuterClass.GetSessionResponse.getDefaultInstance());
      }


      public com.google.protobuf.Empty invalidateSession(
          com.google.protobuf.RpcController controller,
          ru.weber.auth.service.service.grpc.SessionServiceOuterClass.SetSessionInvalidRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.google.protobuf.Empty) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.google.protobuf.Empty.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:ru.weber.auth.service.service.grpc.SessionService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_weber_auth_service_service_grpc_GetSessionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_weber_auth_service_service_grpc_GetSessionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_weber_auth_service_service_grpc_SetSessionInvalidRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_weber_auth_service_service_grpc_SetSessionInvalidRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_MetaInfoEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_MetaInfoEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025session_service.proto\022\"ru.weber.auth.s" +
      "ervice.service.grpc\032\033google/protobuf/emp" +
      "ty.proto\"\"\n\021GetSessionRequest\022\r\n\005token\030\001" +
      " \001(\t\")\n\030SetSessionInvalidRequest\022\r\n\005toke" +
      "n\030\001 \001(\t\"\236\001\n\022GetSessionResponse\022W\n\tmeta_i" +
      "nfo\030\001 \003(\0132D.ru.weber.auth.service.servic" +
      "e.grpc.GetSessionResponse.MetaInfoEntry\032" +
      "/\n\rMetaInfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\0012\370\001\n\016SessionService\022{\n\nGetSessio" +
      "n\0225.ru.weber.auth.service.service.grpc.G" +
      "etSessionRequest\0326.ru.weber.auth.service" +
      ".service.grpc.GetSessionResponse\022i\n\021Inva" +
      "lidateSession\022<.ru.weber.auth.service.se" +
      "rvice.grpc.SetSessionInvalidRequest\032\026.go" +
      "ogle.protobuf.EmptyB\003\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_ru_weber_auth_service_service_grpc_GetSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_weber_auth_service_service_grpc_GetSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_weber_auth_service_service_grpc_GetSessionRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_ru_weber_auth_service_service_grpc_SetSessionInvalidRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_weber_auth_service_service_grpc_SetSessionInvalidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_weber_auth_service_service_grpc_SetSessionInvalidRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_descriptor,
        new java.lang.String[] { "MetaInfo", });
    internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_MetaInfoEntry_descriptor =
      internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_descriptor.getNestedTypes().get(0);
    internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_MetaInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_weber_auth_service_service_grpc_GetSessionResponse_MetaInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
