grpc:
  server:
    address: ${GRPC_ADDRESS:*}
    port: ${GRPC_PORT:9093}

spring:
  datasource:
    url: ${POSTGRESQL_JDBC_URL}
    driver-class-name: ${POSTGRESQL_JDBC_DRIVER:org.postgresql.Driver}
    username: ${POSTGRESQL_JDBC_USERNAME}
    password: ${POSTGRESQL_JDBC_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
      jdbc:
        lob:
          non_contextual_creation: true
      dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

  flyway:
    baseline-on-migrate: true
    locations: classpath:db.migration

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    web-application-type: NONE
app:
  public-key: ${PUBLIC_KEY}